[package]
name = "ml-features"
version = "0.1.0"
authors = ["Elie Génard <elie.genard@laposte.net>"]
edition = "2018"

[dependencies]
ml-features-derive = { version = "0.1.0", path = "ml-features-derive" }

[workspace]
members = ["ml-features-derive"]
